version: '2.2'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "petclinic-datavolume:/var/lib/mysql"

  petclinic:
    depends_on:
    - db
    image: akhilreddyjirra/petclinic:v2
    # image: <dockerhub_username>/petclinic:<tag_version>
    build:
      context: .
    ports:
     - "8080:8080"
#    mem_limit: 700m
#    mem_reservation: 100m

volumes:
  petclinic-datavolume: